/**
 * Manifest of official CBSE Sample Question Papers (SQP) + Marking Schemes (MS).
 *
 * Source: cbseacademic.nic.in (CBSE's official academic site)
 * License: Free for educational use, redistributable with attribution to CBSE.
 *
 * To add new years, get URLs from:
 *   https://cbseacademic.nic.in/SQP_CLASSX_<year>.html
 *   https://cbseacademic.nic.in/SQP_CLASSXII_<year>.html
 */

export type CBSEPaper = {
  class: 10 | 12;
  /** Our internal subject ID (matches SUBJECTS_BY_CLASS) */
  subject: string;
  /** Display name */
  displayName: string;
  /** Academic year the paper was released for, e.g. 2024 means 2024-25 session */
  year: number;
  /** Path under https://cbseacademic.nic.in/ */
  sqpPath: string;
  msPath: string;
  /** If true, the PDF contains heavy math/diagrams — parsing will be patchy. */
  mathHeavy?: boolean;
};

const BASE = "https://cbseacademic.nic.in/";
export const cbseUrl = (path: string) => BASE + path;

export const CBSE_PAPERS_2024_25: CBSEPaper[] = [
  /* ─── CLASS 10 ─── */
  {
    class: 10,
    subject: "math",
    displayName: "Mathematics (Standard)",
    year: 2024,
    sqpPath: "web_material/SQP/ClassX_2024_25/MathsStandard-SQP.pdf",
    msPath: "web_material/SQP/ClassX_2024_25/MathsStandard-MS.pdf",
    mathHeavy: true,
  },
  {
    class: 10,
    subject: "science",
    displayName: "Science",
    year: 2024,
    sqpPath: "web_material/SQP/ClassX_2024_25/Science-SQP.pdf",
    msPath: "web_material/SQP/ClassX_2024_25/Science-MS.pdf",
    mathHeavy: true,
  },
  {
    class: 10,
    subject: "sst",
    displayName: "Social Science",
    year: 2024,
    sqpPath: "web_material/SQP/ClassX_2024_25/SocialScience-SQP.pdf",
    msPath: "web_material/SQP/ClassX_2024_25/SocialScience-MS.pdf",
  },
  {
    class: 10,
    subject: "english",
    displayName: "English (Language & Literature)",
    year: 2024,
    sqpPath: "web_material/SQP/ClassX_2024_25/EnglishL-SQP.pdf",
    msPath: "web_material/SQP/ClassX_2024_25/EnglishL-MS.pdf",
  },
  {
    class: 10,
    subject: "hindi",
    displayName: "Hindi A",
    year: 2024,
    sqpPath: "web_material/SQP/ClassX_2024_25/HindiCourseA-SQP.pdf",
    msPath: "web_material/SQP/ClassX_2024_25/HindiCourseA-MS.pdf",
  },

  /* ─── CLASS 12 ─── */
  {
    class: 12,
    subject: "math",
    displayName: "Mathematics",
    year: 2024,
    sqpPath: "web_material/SQP/ClassXII_2024_25/Maths-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2024_25/Maths-MS.pdf",
    mathHeavy: true,
  },
  {
    class: 12,
    subject: "physics",
    displayName: "Physics",
    year: 2024,
    sqpPath: "web_material/SQP/ClassXII_2024_25/Physics-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2024_25/Physics-MS.pdf",
    mathHeavy: true,
  },
  {
    class: 12,
    subject: "chemistry",
    displayName: "Chemistry",
    year: 2024,
    sqpPath: "web_material/SQP/ClassXII_2024_25/Chemistry-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2024_25/Chemistry-MS.pdf",
    mathHeavy: true,
  },
  {
    class: 12,
    subject: "biology",
    displayName: "Biology",
    year: 2024,
    sqpPath: "web_material/SQP/ClassXII_2024_25/Biology-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2024_25/Biology-MS.pdf",
  },
  {
    class: 12,
    subject: "english",
    displayName: "English Core",
    year: 2024,
    sqpPath: "web_material/SQP/ClassXII_2024_25/EnglishCore-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2024_25/EnglishCore-MS.pdf",
  },
  {
    class: 12,
    subject: "hindi",
    displayName: "Hindi Core",
    year: 2024,
    sqpPath: "web_material/SQP/ClassXII_2024_25/HindiCore-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2024_25/HindiCore-MS.pdf",
  },
  {
    class: 12,
    subject: "accountancy",
    displayName: "Accountancy",
    year: 2024,
    sqpPath: "web_material/SQP/ClassXII_2024_25/Accountancy-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2024_25/Accountancy-MS.pdf",
  },
  {
    class: 12,
    subject: "business",
    displayName: "Business Studies",
    year: 2024,
    sqpPath: "web_material/SQP/ClassXII_2024_25/BusinessStudies-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2024_25/BusinessStudies-MS.pdf",
  },
  {
    class: 12,
    subject: "economics",
    displayName: "Economics",
    year: 2024,
    sqpPath: "web_material/SQP/ClassXII_2024_25/Economics-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2024_25/Economics-MS.pdf",
  },
  {
    class: 12,
    subject: "history",
    displayName: "History",
    year: 2024,
    sqpPath: "web_material/SQP/ClassXII_2024_25/History-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2024_25/History-MS.pdf",
  },
  {
    class: 12,
    subject: "geography",
    displayName: "Geography",
    year: 2024,
    sqpPath: "web_material/SQP/ClassXII_2024_25/Geography-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2024_25/Geography-MS.pdf",
  },
  {
    class: 12,
    subject: "polsci",
    displayName: "Political Science",
    year: 2024,
    sqpPath: "web_material/SQP/ClassXII_2024_25/PolSci-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2024_25/PolSci-MS.pdf",
  },
  {
    class: 12,
    subject: "psychology",
    displayName: "Psychology",
    year: 2024,
    sqpPath: "web_material/SQP/ClassXII_2024_25/Psychology-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2024_25/Psychology-MS.pdf",
  },
  {
    class: 12,
    subject: "sociology",
    displayName: "Sociology",
    year: 2024,
    sqpPath: "web_material/SQP/ClassXII_2024_25/Sociology-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2024_25/Sociology-MS.pdf",
  },
  {
    class: 12,
    subject: "cs",
    displayName: "Computer Science",
    year: 2024,
    sqpPath: "web_material/SQP/ClassXII_2024_25/ComputerScience-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2024_25/ComputerScience-MS.pdf",
    mathHeavy: true,
  },

  /* ─── PRIOR YEAR (2023-24 session) — more PYQ depth ─── */

  /* Class 10 */
  { class: 10, subject: "math", displayName: "Mathematics (Standard)", year: 2023,
    sqpPath: "web_material/SQP/ClassX_2023_24/MathsStandard-SQP.pdf",
    msPath: "web_material/SQP/ClassX_2023_24/MathsStandard-MS.pdf", mathHeavy: true },
  { class: 10, subject: "science", displayName: "Science", year: 2023,
    sqpPath: "web_material/SQP/ClassX_2023_24/Science-SQP.pdf",
    msPath: "web_material/SQP/ClassX_2023_24/Science-MS.pdf", mathHeavy: true },
  { class: 10, subject: "sst", displayName: "Social Science", year: 2023,
    sqpPath: "web_material/SQP/ClassX_2023_24/SocialScience-SQP.pdf",
    msPath: "web_material/SQP/ClassX_2023_24/SocialScience-MS.pdf" },
  { class: 10, subject: "english", displayName: "English (Language & Literature)", year: 2023,
    sqpPath: "web_material/SQP/ClassX_2023_24/EnglishL-SQP.pdf",
    msPath: "web_material/SQP/ClassX_2023_24/EnglishL-MS.pdf" },
  { class: 10, subject: "hindi", displayName: "Hindi A", year: 2023,
    sqpPath: "web_material/SQP/ClassX_2023_24/HindiCourseA-SQP.pdf",
    msPath: "web_material/SQP/ClassX_2023_24/HindiCourseA-MS.pdf" },

  /* Class 12 */
  { class: 12, subject: "math", displayName: "Mathematics", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Maths-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Maths-MS.pdf", mathHeavy: true },
  { class: 12, subject: "physics", displayName: "Physics", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Physics-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Physics-MS.pdf", mathHeavy: true },
  { class: 12, subject: "chemistry", displayName: "Chemistry", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Chemistry-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Chemistry-MS.pdf", mathHeavy: true },
  { class: 12, subject: "biology", displayName: "Biology", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Biology-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Biology-MS.pdf" },
  { class: 12, subject: "english", displayName: "English Core", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/EnglishCore-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/EnglishCore-MS.pdf" },
  { class: 12, subject: "hindi", displayName: "Hindi Core", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/HindiCore-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/HindiCore-MS.pdf" },
  { class: 12, subject: "accountancy", displayName: "Accountancy", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Accountancy-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Accountancy-MS.pdf" },
  { class: 12, subject: "business", displayName: "Business Studies", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/BusinessStudies-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/BusinessStudies-MS.pdf" },
  { class: 12, subject: "economics", displayName: "Economics", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Economics-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Economics-MS.pdf" },
  { class: 12, subject: "history", displayName: "History", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/History-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/History-MS.pdf" },
  { class: 12, subject: "geography", displayName: "Geography", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Geography-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Geography-MS.pdf" },
  { class: 12, subject: "polsci", displayName: "Political Science", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/PolSci-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/PolSci-MS.pdf" },
  { class: 12, subject: "psychology", displayName: "Psychology", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Psychology-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Psychology-MS.pdf" },
  { class: 12, subject: "sociology", displayName: "Sociology", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Sociology-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Sociology-MS.pdf" },
  { class: 12, subject: "cs", displayName: "Computer Science", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/ComputerScience-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/ComputerScience-MS.pdf", mathHeavy: true },

  /* ════════════════════════════════════════════════════════════════
     2025-26 LATEST SQPs (for upcoming Boards 2027)
     ════════════════════════════════════════════════════════════════ */
  { class: 12, subject: "math", displayName: "Mathematics", year: 2025,
    sqpPath: "web_material/SQP/ClassXII_2025_26/Maths-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2025_26/Maths-MS.pdf", mathHeavy: true },
  { class: 12, subject: "physics", displayName: "Physics", year: 2025,
    sqpPath: "web_material/SQP/ClassXII_2025_26/Physics-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2025_26/Physics-MS.pdf", mathHeavy: true },
  { class: 12, subject: "chemistry", displayName: "Chemistry", year: 2025,
    sqpPath: "web_material/SQP/ClassXII_2025_26/Chemistry-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2025_26/Chemistry-MS.pdf", mathHeavy: true },
  { class: 12, subject: "biology", displayName: "Biology", year: 2025,
    sqpPath: "web_material/SQP/ClassXII_2025_26/Biology-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2025_26/Biology-MS.pdf" },
  { class: 12, subject: "english", displayName: "English Core", year: 2025,
    sqpPath: "web_material/SQP/ClassXII_2025_26/EnglishCore-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2025_26/EnglishCore-MS.pdf" },
  { class: 12, subject: "accountancy", displayName: "Accountancy", year: 2025,
    sqpPath: "web_material/SQP/ClassXII_2025_26/Accountancy-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2025_26/Accountancy-MS.pdf" },
  { class: 12, subject: "business", displayName: "Business Studies", year: 2025,
    sqpPath: "web_material/SQP/ClassXII_2025_26/BusinessStudies-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2025_26/BusinessStudies-MS.pdf" },
  { class: 12, subject: "economics", displayName: "Economics", year: 2025,
    sqpPath: "web_material/SQP/ClassXII_2025_26/Economics-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2025_26/Economics-MS.pdf" },
  { class: 12, subject: "history", displayName: "History", year: 2025,
    sqpPath: "web_material/SQP/ClassXII_2025_26/History-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2025_26/History-MS.pdf" },
  { class: 12, subject: "geography", displayName: "Geography", year: 2025,
    sqpPath: "web_material/SQP/ClassXII_2025_26/Geography-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2025_26/Geography-MS.pdf" },
  { class: 12, subject: "polsci", displayName: "Political Science", year: 2025,
    sqpPath: "web_material/SQP/ClassXII_2025_26/PolSci-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2025_26/PolSci-MS.pdf" },
  { class: 12, subject: "cs", displayName: "Computer Science", year: 2025,
    sqpPath: "web_material/SQP/ClassXII_2025_26/ComputerScience-SQP.pdf",
    msPath: "web_material/SQP/ClassXII_2025_26/ComputerScience-MS.pdf", mathHeavy: true },
];

/**
 * ADDITIONAL PRACTICE QUESTIONS (PQ + PQ MS) — separate from SQPs.
 * CBSE releases extra practice question sets each year, free + redistributable.
 * Available for 2021-22, 2022-23, 2023-24. Some subjects have Set 1 + Set 2.
 */
export const CBSE_PRACTICE_QUESTIONS: CBSEPaper[] = [
  /* ─── 2023-24 Class 12 — Set 1 ─── */
  { class: 12, subject: "accountancy", displayName: "Accountancy (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Accountancy-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Accountancy-PQMS.pdf" },
  { class: 12, subject: "biology", displayName: "Biology (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Biology-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Biology-PQMS.pdf" },
  { class: 12, subject: "business", displayName: "Business Studies (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/BST_PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/BST_PQMS.pdf" },
  { class: 12, subject: "chemistry", displayName: "Chemistry (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Chemistry-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Chemistry-PQMS.pdf", mathHeavy: true },
  { class: 12, subject: "cs", displayName: "Computer Science (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/CS_PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/CS_PQMS.pdf", mathHeavy: true },
  { class: 12, subject: "economics", displayName: "Economics (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Economics_PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Economics_PQMS.pdf" },
  { class: 12, subject: "english", displayName: "English Core (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/EnglishCore-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/EnglishCore-PQMS.pdf" },
  { class: 12, subject: "geography", displayName: "Geography (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Geography-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Geography-PQMS.pdf" },
  { class: 12, subject: "history", displayName: "History (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/History-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/History-PQMS.pdf" },
  { class: 12, subject: "math", displayName: "Mathematics (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Maths-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Maths-PQMS.pdf", mathHeavy: true },
  { class: 12, subject: "physics", displayName: "Physics (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Physics-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Physics-PQMS.pdf", mathHeavy: true },
  { class: 12, subject: "psychology", displayName: "Psychology (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Psychology_PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Psychology_PQMS.pdf" },

  /* ─── 2023-24 Class 12 — Set 2 ─── */
  { class: 12, subject: "accountancy", displayName: "Accountancy (PQ 23-24 Set 2)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Accountancy-PQ2.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Accountancy-PQMS2.pdf" },
  { class: 12, subject: "biology", displayName: "Biology (PQ 23-24 Set 2)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Biology-PQ2.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Biology-PQMS2.pdf" },
  { class: 12, subject: "business", displayName: "Business Studies (PQ 23-24 Set 2)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/BST_PQ2.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/BST_PQMS2.pdf" },
  { class: 12, subject: "chemistry", displayName: "Chemistry (PQ 23-24 Set 2)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Chemistry-PQ2.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Chemistry-PQMS2.pdf", mathHeavy: true },
  { class: 12, subject: "economics", displayName: "Economics (PQ 23-24 Set 2)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Economics_PQ2.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Economics_PQMS2.pdf" },
  { class: 12, subject: "english", displayName: "English Core (PQ 23-24 Set 2)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/EnglishCore-PQ2.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/EnglishCore-PQMS2.pdf" },
  { class: 12, subject: "geography", displayName: "Geography (PQ 23-24 Set 2)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Geography-PQ2.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Geography-PQMS2.pdf" },
  { class: 12, subject: "history", displayName: "History (PQ 23-24 Set 2)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/History-PQ2.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/History-PQMS2.pdf" },
  { class: 12, subject: "math", displayName: "Mathematics (PQ 23-24 Set 2)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Maths-PQ2.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Maths-PQMS2.pdf", mathHeavy: true },
  { class: 12, subject: "physics", displayName: "Physics (PQ 23-24 Set 2)", year: 2023,
    sqpPath: "web_material/SQP/ClassXII_2023_24/Physics-PQ2.pdf",
    msPath: "web_material/SQP/ClassXII_2023_24/Physics-PQMS2.pdf", mathHeavy: true },

  /* ─── 2023-24 Class 10 ─── */
  { class: 10, subject: "math", displayName: "Mathematics (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassX_2023_24/Mathematics-PQ.pdf",
    msPath: "web_material/SQP/ClassX_2023_24/Mathematics-PQMS.pdf", mathHeavy: true },
  { class: 10, subject: "math", displayName: "Mathematics (PQ 23-24 Set 2)", year: 2023,
    sqpPath: "web_material/SQP/ClassX_2023_24/Mathematics-PQ2.pdf",
    msPath: "web_material/SQP/ClassX_2023_24/Mathematics-PQMS2.pdf", mathHeavy: true },
  { class: 10, subject: "science", displayName: "Science (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassX_2023_24/Science-PQ.pdf",
    msPath: "web_material/SQP/ClassX_2023_24/Science-PQMS.pdf", mathHeavy: true },
  { class: 10, subject: "science", displayName: "Science (PQ 23-24 Set 2)", year: 2023,
    sqpPath: "web_material/SQP/ClassX_2023_24/Science-PQ2.pdf",
    msPath: "web_material/SQP/ClassX_2023_24/Science-PQMS2.pdf", mathHeavy: true },
  { class: 10, subject: "sst", displayName: "Social Science (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassX_2023_24/SS-PQ.pdf",
    msPath: "web_material/SQP/ClassX_2023_24/SS-PQMS.pdf" },
  { class: 10, subject: "sst", displayName: "Social Science (PQ 23-24 Set 2)", year: 2023,
    sqpPath: "web_material/SQP/ClassX_2023_24/SS-PQ2.pdf",
    msPath: "web_material/SQP/ClassX_2023_24/SS-PQMS2.pdf" },
  { class: 10, subject: "english", displayName: "English (PQ 23-24 Set 1)", year: 2023,
    sqpPath: "web_material/SQP/ClassX_2023_24/English-PQ.pdf",
    msPath: "web_material/SQP/ClassX_2023_24/English-PQMS.pdf" },

  /* ─── 2022-23 Class 12 ─── */
  { class: 12, subject: "accountancy", displayName: "Accountancy (PQ 22-23)", year: 2022,
    sqpPath: "web_material/SQP/ClassXII_2022_23/Accountancy-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2022_23/Accountancy-PQMS.pdf" },
  { class: 12, subject: "biology", displayName: "Biology (PQ 22-23)", year: 2022,
    sqpPath: "web_material/SQP/ClassXII_2022_23/Biology-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2022_23/Biology-PQMS.pdf" },
  { class: 12, subject: "business", displayName: "Business Studies (PQ 22-23)", year: 2022,
    sqpPath: "web_material/SQP/ClassXII_2022_23/BST_PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2022_23/BST_PQMS.pdf" },
  { class: 12, subject: "chemistry", displayName: "Chemistry (PQ 22-23)", year: 2022,
    sqpPath: "web_material/SQP/ClassXII_2022_23/Chemistry-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2022_23/Chemistry-PQMS.pdf", mathHeavy: true },
  { class: 12, subject: "economics", displayName: "Economics (PQ 22-23)", year: 2022,
    sqpPath: "web_material/SQP/ClassXII_2022_23/Economics_PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2022_23/Economics_PQMS.pdf" },
  { class: 12, subject: "english", displayName: "English Core (PQ 22-23)", year: 2022,
    sqpPath: "web_material/SQP/ClassXII_2022_23/EnglishCore-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2022_23/EnglishCore-PQMS.pdf" },
  { class: 12, subject: "geography", displayName: "Geography (PQ 22-23)", year: 2022,
    sqpPath: "web_material/SQP/ClassXII_2022_23/Geography-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2022_23/Geography-PQMS.pdf" },
  { class: 12, subject: "history", displayName: "History (PQ 22-23)", year: 2022,
    sqpPath: "web_material/SQP/ClassXII_2022_23/History-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2022_23/History-PQMS.pdf" },
  { class: 12, subject: "math", displayName: "Mathematics (PQ 22-23)", year: 2022,
    sqpPath: "web_material/SQP/ClassXII_2022_23/Maths-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2022_23/Maths-PQMS.pdf", mathHeavy: true },
  { class: 12, subject: "physics", displayName: "Physics (PQ 22-23)", year: 2022,
    sqpPath: "web_material/SQP/ClassXII_2022_23/Physics-PQ.pdf",
    msPath: "web_material/SQP/ClassXII_2022_23/Physics-PQMS.pdf", mathHeavy: true },

  /* ─── 2022-23 Class 10 ─── */
  { class: 10, subject: "math", displayName: "Mathematics (PQ 22-23)", year: 2022,
    sqpPath: "web_material/SQP/ClassX_2022_23/Mathematics-PQ.pdf",
    msPath: "web_material/SQP/ClassX_2022_23/Mathematics-PQMS.pdf", mathHeavy: true },
  { class: 10, subject: "science", displayName: "Science (PQ 22-23)", year: 2022,
    sqpPath: "web_material/SQP/ClassX_2022_23/Science-PQ.pdf",
    msPath: "web_material/SQP/ClassX_2022_23/Science-PQMS.pdf", mathHeavy: true },
  { class: 10, subject: "sst", displayName: "Social Science (PQ 22-23)", year: 2022,
    sqpPath: "web_material/SQP/ClassX_2022_23/SS-PQ.pdf",
    msPath: "web_material/SQP/ClassX_2022_23/SS-PQMS.pdf" },
  { class: 10, subject: "english", displayName: "English (PQ 22-23)", year: 2022,
    sqpPath: "web_material/SQP/ClassX_2022_23/English-PQ.pdf",
    msPath: "web_material/SQP/ClassX_2022_23/English-PQMS.pdf" },
];
