/**
 * Extended entrance exam catalog (~35 new entries) covering India + international.
 *
 * Each exam has: how-to-apply step list, careers it unlocks, colleges that
 * accept it. Career + college names are resolved against the Career and
 * College collections during seeding.
 *
 * Date format ISO. Dates marked "Annual cycle" stay open-ended.
 */

export type SeedExamExtended = {
  name: string;
  fullName: string;
  category: "entrance" | "scholarship" | "olympiad" | "board";
  field?: string;
  level?: "UG" | "PG" | "defense" | "research" | "language" | "lateral";
  international?: boolean;
  examDate?: string;
  applicationStart?: string;
  applicationEnd?: string;
  eligibility?: string;
  syllabus?: string;
  pattern?: string;
  applyHow?: string[];
  officialWebsite?: string;
  fees?: number;
  description?: string;
  careersUnlocked?: string[];
  collegesAccepting?: string[];
};

export const EXAMS_EXTENDED: SeedExamExtended[] = [
  /* ═══════════════════════════════════════════════════════════════
     ENGINEERING (INDIA)
     ═══════════════════════════════════════════════════════════════ */
  {
    name: "VITEEE",
    fullName: "VIT Engineering Entrance Examination",
    category: "entrance",
    field: "engineering",
    level: "UG",
    examDate: "2026-04-15",
    applicationStart: "2025-12-01",
    applicationEnd: "2026-03-31",
    eligibility: "Class 12 with PCM, minimum 60% (50% for SC/ST). Maximum age ~25.",
    pattern: "125 MCQs · Physics, Chemistry, Math/Bio, English, Aptitude · 2.5 hrs · CBT",
    fees: 1350,
    officialWebsite: "https://viteee.vit.ac.in",
    description: "Entrance to VIT Vellore, Chennai, Amaravati, Bhopal — among the largest private engineering networks in India.",
    applyHow: [
      "Register on viteee.vit.ac.in with mobile + email",
      "Fill personal + academic + slot preference details",
      "Upload photo + signature + Class 10 marksheet",
      "Pay ₹1,350 application fee (online)",
      "Download admit card 2-3 weeks before exam",
      "Take CBT at chosen test centre, score available within 7 days",
    ],
    careersUnlocked: ["Software Engineer", "Mechanical Engineer", "Civil Engineer", "Electrical Engineer", "Robotics Engineer", "Data Engineer"],
    collegesAccepting: ["VIT Vellore", "VIT Chennai", "VIT Bhopal", "VIT Amaravati"],
  },
  {
    name: "SRMJEEE",
    fullName: "SRM Joint Engineering Entrance Examination",
    category: "entrance",
    field: "engineering",
    level: "UG",
    examDate: "2026-04-25",
    applicationStart: "2025-11-15",
    applicationEnd: "2026-04-10",
    eligibility: "Class 12 with PCM, minimum 60%.",
    pattern: "Physics, Chemistry, Math/Bio, English, Aptitude · 2.5 hrs · CBT",
    fees: 1400,
    officialWebsite: "https://applications.srmist.edu.in",
    description: "Admission to SRM Institutes — Chennai, NCR, Sikkim, AP.",
    applyHow: [
      "Register on applications.srmist.edu.in",
      "Choose campus preference + course",
      "Upload documents + pay ₹1,400 fee",
      "Book slot from available windows",
      "Counselling based on rank — pay tuition advance after seat allotment",
    ],
    careersUnlocked: ["Software Engineer", "Mechanical Engineer", "AI/ML Engineer", "DevOps / Cloud Engineer"],
    collegesAccepting: ["SRM University Chennai", "SRM University AP"],
  },
  {
    name: "COMEDK UGET",
    fullName: "Consortium of Medical, Engineering and Dental Colleges of Karnataka",
    category: "entrance",
    field: "engineering",
    level: "UG",
    examDate: "2026-05-10",
    applicationStart: "2026-01-20",
    applicationEnd: "2026-04-20",
    eligibility: "Class 12 with PCM ≥45% (40% for SC/ST/OBC).",
    pattern: "Physics, Chemistry, Math · 180 MCQs · 3 hrs · CBT",
    fees: 1800,
    officialWebsite: "https://www.comedk.org",
    description: "Common entrance for ~190 private engineering colleges in Karnataka. Counselling separate from KCET.",
    careersUnlocked: ["Software Engineer", "Mechanical Engineer", "Civil Engineer", "Electronics Engineer"],
    collegesAccepting: ["RV College of Engineering Bangalore", "BMS College of Engineering", "PES University", "MS Ramaiah Institute"],
  },
  {
    name: "MHT-CET",
    fullName: "Maharashtra Common Entrance Test",
    category: "entrance",
    field: "engineering",
    level: "UG",
    examDate: "2026-05-05",
    applicationStart: "2026-01-15",
    applicationEnd: "2026-04-05",
    eligibility: "Maharashtra domicile preferred. Class 12 PCM ≥50%.",
    pattern: "Physics + Chemistry (100 MCQs, 90 min) + Math (50 MCQs, 90 min)",
    fees: 1000,
    officialWebsite: "https://cetcell.mahacet.org",
    description: "Engineering + Pharmacy admission across 350+ Maharashtra colleges. Separate counselling via DTE Maharashtra.",
    careersUnlocked: ["Software Engineer", "Mechanical Engineer", "Civil Engineer", "Pharmacist"],
    collegesAccepting: ["COEP Pune", "VJTI Mumbai", "MIT Pune", "Sardar Patel Mumbai"],
  },
  {
    name: "KCET",
    fullName: "Karnataka Common Entrance Test",
    category: "entrance",
    field: "engineering",
    level: "UG",
    examDate: "2026-04-20",
    applicationStart: "2026-01-25",
    applicationEnd: "2026-03-25",
    eligibility: "Karnataka domicile. Class 12 PCM ≥45%.",
    pattern: "Physics + Chemistry + Math + Biology · 60 MCQs each · 3 hrs",
    fees: 800,
    officialWebsite: "https://kea.kar.nic.in",
    description: "Karnataka govt + aided engineering / pharmacy / agriculture / veterinary seats.",
    careersUnlocked: ["Software Engineer", "Mechanical Engineer", "Veterinarian", "Pharmacist"],
    collegesAccepting: ["UVCE Bangalore", "NIE Mysuru", "Bangalore University"],
  },
  {
    name: "WBJEE",
    fullName: "West Bengal Joint Entrance Examination",
    category: "entrance",
    field: "engineering",
    level: "UG",
    examDate: "2026-04-26",
    applicationStart: "2025-12-15",
    applicationEnd: "2026-02-15",
    eligibility: "Class 12 PCM ≥45%. WB domicile for state quota.",
    pattern: "Math (75 Q, 100 marks) + Physics + Chem (75 Q each, 50 marks each) · 4 hrs",
    fees: 500,
    officialWebsite: "https://wbjeeb.nic.in",
    description: "West Bengal engineering + pharmacy + architecture seats.",
    careersUnlocked: ["Software Engineer", "Civil Engineer", "Architect", "Pharmacist"],
    collegesAccepting: ["Jadavpur University Kolkata", "IIEST Shibpur"],
  },

  /* ═══════════════════════════════════════════════════════════════
     ARCHITECTURE + DESIGN
     ═══════════════════════════════════════════════════════════════ */
  {
    name: "NATA",
    fullName: "National Aptitude Test in Architecture",
    category: "entrance",
    field: "architecture",
    level: "UG",
    examDate: "2026-03-15",
    applicationStart: "2026-01-10",
    applicationEnd: "2026-03-05",
    eligibility: "Class 12 with Math + ≥50% aggregate (40% for reserved). Drawing aptitude.",
    pattern: "Drawing + Aesthetic Sensitivity + Math (CBT + drawing) · 3 hrs",
    fees: 2000,
    officialWebsite: "https://www.nata.in",
    description: "Architecture (B.Arch) entrance accepted by 300+ colleges. Held 3 times a year — best score counts.",
    applyHow: [
      "Register on nata.in with email + phone",
      "Fill personal + academic details",
      "Upload photo + signature + Class 12 marksheet",
      "Pay ₹2,000 fee per session",
      "Book preferred date from available slots",
      "Take CBT + drawing test at centre",
    ],
    careersUnlocked: ["Architect"],
    collegesAccepting: ["SPA Delhi", "SPA Bhopal", "SPA Vijayawada", "JJ College of Architecture Mumbai", "CEPT Ahmedabad", "RV School of Architecture"],
  },
  {
    name: "UCEED",
    fullName: "Undergraduate Common Entrance Examination for Design",
    category: "entrance",
    field: "design",
    level: "UG",
    examDate: "2026-01-19",
    applicationStart: "2025-10-10",
    applicationEnd: "2025-11-10",
    eligibility: "Class 12 (any stream). Born on/after Oct 1, 2005 (for 2026 cycle).",
    pattern: "Visualisation, Observation, Mental Ability, Design Sensitivity, Drawing · 3 hrs · CBT + drawing",
    fees: 3000,
    officialWebsite: "https://www.uceed.iitb.ac.in",
    description: "Entry to B.Des at IIT Bombay, IIT Delhi, IIT Guwahati and IIITDM Jabalpur. The toughest design entrance in India.",
    careersUnlocked: ["Graphic / UI Designer", "Fashion Designer", "3D Animator / VFX Artist"],
    collegesAccepting: ["IIT Bombay IDC", "IIT Delhi", "IIT Guwahati", "IIITDM Jabalpur"],
  },
  {
    name: "Pearl Academy Entrance",
    fullName: "Pearl Academy Entrance Exam + Portfolio Review",
    category: "entrance",
    field: "design",
    level: "UG",
    applicationStart: "2025-12-01",
    applicationEnd: "2026-05-15",
    eligibility: "Class 12 pass in any stream.",
    pattern: "Online creative aptitude test + portfolio + personal interview",
    fees: 1500,
    officialWebsite: "https://www.pearlacademy.com",
    description: "Top private design school — fashion, communication design, jewellery, business design. Multiple campuses.",
    careersUnlocked: ["Fashion Designer", "Graphic / UI Designer"],
    collegesAccepting: ["Pearl Academy Delhi", "Pearl Academy Mumbai", "Pearl Academy Jaipur"],
  },
  {
    name: "Symbiosis SET Design",
    fullName: "Symbiosis Entrance Test (SID Pune Design)",
    category: "entrance",
    field: "design",
    level: "UG",
    examDate: "2026-05-12",
    applicationStart: "2026-01-15",
    applicationEnd: "2026-04-30",
    eligibility: "Class 12 with ≥50%.",
    pattern: "SET General + SEED + Personal Interaction Round",
    fees: 1750,
    officialWebsite: "https://www.set-test.org",
    description: "Symbiosis Institute of Design Pune — known for fashion communication + product design.",
    careersUnlocked: ["Fashion Designer", "Graphic / UI Designer"],
    collegesAccepting: ["Symbiosis Institute of Design Pune"],
  },

  /* ═══════════════════════════════════════════════════════════════
     LAW
     ═══════════════════════════════════════════════════════════════ */
  {
    name: "SLAT",
    fullName: "Symbiosis Law Admission Test",
    category: "entrance",
    field: "law",
    level: "UG",
    examDate: "2026-05-02",
    applicationStart: "2025-12-25",
    applicationEnd: "2026-04-15",
    eligibility: "Class 12 pass ≥45% (40% for reserved).",
    pattern: "Logical Reasoning, Legal Reasoning, Analytical, Reading Comprehension, General Knowledge · 60 MCQs · 60 min",
    fees: 2250,
    officialWebsite: "https://www.set-test.org",
    description: "Entrance to Symbiosis Law Schools in Pune, Noida, Hyderabad, Nagpur.",
    careersUnlocked: ["Lawyer", "Constitutional / Human Rights Lawyer", "Cyber Lawyer", "Intellectual Property Lawyer"],
    collegesAccepting: ["Symbiosis Law School Pune", "Symbiosis Law School Hyderabad", "Symbiosis Law School Noida"],
  },
  {
    name: "MH-CET Law",
    fullName: "Maharashtra Common Entrance Test — Law (5 yr + 3 yr)",
    category: "entrance",
    field: "law",
    level: "UG",
    examDate: "2026-04-12",
    applicationStart: "2026-01-20",
    applicationEnd: "2026-03-30",
    eligibility: "5-yr: Class 12 ≥45%. 3-yr: UG degree ≥45%.",
    pattern: "Legal Aptitude, Logical Reasoning, English, GK, Math · 150 MCQs · 2 hrs",
    fees: 1000,
    officialWebsite: "https://cetcell.mahacet.org",
    description: "Maharashtra govt + aided law college admission. Separate 5-yr and 3-yr tests.",
    careersUnlocked: ["Lawyer", "Tax Lawyer / Chartered Tax Practitioner"],
    collegesAccepting: ["ILS Pune", "Government Law College Mumbai"],
  },

  /* ═══════════════════════════════════════════════════════════════
     MANAGEMENT
     ═══════════════════════════════════════════════════════════════ */
  {
    name: "XAT",
    fullName: "Xavier Aptitude Test",
    category: "entrance",
    field: "management",
    level: "PG",
    examDate: "2026-01-05",
    applicationStart: "2025-08-10",
    applicationEnd: "2025-11-30",
    eligibility: "UG degree (any discipline).",
    pattern: "VARC + DM + QA + GK + Essay · 3.5 hrs · CBT",
    fees: 2100,
    officialWebsite: "https://xatonline.in",
    description: "XLRI Jamshedpur's flagship entrance — accepted by 160+ B-schools. Known for the Decision Making section.",
    careersUnlocked: ["Investment Banker", "Marketing Manager", "HR Manager / Talent Acquisition Lead", "Brand Manager (FMCG / Consumer)"],
    collegesAccepting: ["XLRI Jamshedpur", "XIM Bhubaneswar", "TAPMI Manipal", "GIM Goa"],
  },
  {
    name: "SNAP",
    fullName: "Symbiosis National Aptitude Test",
    category: "entrance",
    field: "management",
    level: "PG",
    examDate: "2025-12-20",
    applicationStart: "2025-08-25",
    applicationEnd: "2025-11-25",
    eligibility: "UG degree ≥50%.",
    pattern: "General English + Quantitative + Analytical & Logical · 60 MCQs · 60 min",
    fees: 2250,
    officialWebsite: "https://www.snaptest.org",
    description: "Symbiosis B-schools (SIBM Pune, SCMHRD, SIIB, SIOM) entrance.",
    careersUnlocked: ["Marketing Manager", "HR Manager / Talent Acquisition Lead"],
    collegesAccepting: ["SIBM Pune", "SCMHRD Pune", "SIIB Pune"],
  },
  {
    name: "NMAT by GMAC",
    fullName: "Narsee Monjee Management Aptitude Test",
    category: "entrance",
    field: "management",
    level: "PG",
    applicationStart: "2025-08-01",
    applicationEnd: "2025-10-15",
    eligibility: "UG degree.",
    pattern: "Language Skills + Quantitative + Logical Reasoning · 120 MCQs · 2 hrs · Take up to 3 times",
    fees: 2800,
    officialWebsite: "https://www.mba.com/exams/nmat",
    description: "NMIMS Mumbai + other top B-schools. Unique — you can take it up to 3 times in one cycle.",
    careersUnlocked: ["Marketing Manager", "Brand Manager (FMCG / Consumer)", "Investment Banker"],
    collegesAccepting: ["NMIMS Mumbai", "VIT Vellore"],
  },
  {
    name: "CMAT",
    fullName: "Common Management Admission Test",
    category: "entrance",
    field: "management",
    level: "PG",
    examDate: "2026-05-25",
    applicationStart: "2026-02-20",
    applicationEnd: "2026-04-20",
    eligibility: "UG degree.",
    pattern: "Quant + Logical + Language + GK + Innovation & Entrepreneurship · 100 MCQs · 3 hrs · CBT",
    fees: 2000,
    officialWebsite: "https://cmat.nta.nic.in",
    description: "AICTE-approved MBA admission, accepted by 1,000+ B-schools.",
    careersUnlocked: ["Marketing Manager", "HR Manager / Talent Acquisition Lead"],
  },
  {
    name: "IPMAT Indore",
    fullName: "Integrated Programme in Management Aptitude Test",
    category: "entrance",
    field: "management",
    level: "UG",
    examDate: "2026-05-20",
    applicationStart: "2026-03-01",
    applicationEnd: "2026-04-20",
    eligibility: "Class 12 pass with ≥60% (55% for SC/ST). Math in Class 12.",
    pattern: "Quant (SA + MCQ) + Verbal Ability · 2 hrs · CBT",
    fees: 4130,
    officialWebsite: "https://www.iimidr.ac.in/ipm",
    description: "5-year integrated BBA+MBA at IIM Indore — earn an MBA at age 22 directly from school.",
    careersUnlocked: ["Marketing Manager", "Investment Banker", "Brand Manager (FMCG / Consumer)"],
    collegesAccepting: ["IIM Indore", "IIM Rohtak", "IIM Ranchi", "IIM Jammu"],
  },

  /* ═══════════════════════════════════════════════════════════════
     COMMERCE / FINANCE
     ═══════════════════════════════════════════════════════════════ */
  {
    name: "CS Executive Entrance (CSEET)",
    fullName: "Company Secretary Executive Entrance Test",
    category: "entrance",
    field: "commerce",
    level: "UG",
    applicationStart: "2025-11-01",
    applicationEnd: "2025-12-15",
    eligibility: "Class 12 in any stream.",
    pattern: "Business Communication, Legal Aptitude & Logical Reasoning, Economic & Business Environment, Current Affairs · 140 MCQs · 2 hrs",
    fees: 1500,
    officialWebsite: "https://www.icsi.edu",
    description: "Step 1 to becoming a Company Secretary. Held 4 times a year (Jan, May, Jul, Nov).",
    careersUnlocked: ["Company Secretary (CS)"],
  },
  {
    name: "CMA Foundation",
    fullName: "Cost & Management Accountant — Foundation",
    category: "entrance",
    field: "commerce",
    level: "UG",
    applicationStart: "2025-08-01",
    applicationEnd: "2025-10-31",
    eligibility: "Class 12 pass.",
    pattern: "Fundamentals of Economics + Accounts + Laws + Math/Stats · OMR-based",
    fees: 6000,
    officialWebsite: "https://icmai.in",
    description: "Step 1 of the CMA (Cost Accountant) qualification by ICMAI. Held Jun + Dec.",
    careersUnlocked: ["Cost & Management Accountant (CMA)"],
  },
  {
    name: "CFA Level 1",
    fullName: "Chartered Financial Analyst Level 1",
    category: "entrance",
    field: "commerce",
    level: "PG",
    international: true,
    applicationStart: "2025-08-01",
    applicationEnd: "2026-01-15",
    eligibility: "UG degree (final-year students also eligible).",
    pattern: "180 MCQs · 4.5 hrs · CBT · 10 topic areas (Ethics, Quant, Econ, FRA, Corp Issuers, Equity, Fixed Income, Derivatives, Alts, Portfolio Mgmt)",
    fees: 90000,
    officialWebsite: "https://www.cfainstitute.org",
    description: "Globally recognised finance credential. Three levels — typically 3-4 years to charter. ~45% pass rate per level.",
    applyHow: [
      "Register at cfainstitute.org with ID proof",
      "Pay $940 enrollment + exam fee (~₹78,000)",
      "Choose exam window (Feb / May / Aug / Nov)",
      "Schedule slot at Prometric centre in your city",
      "Self-study using CFA Inst curriculum (~300 hrs prep)",
    ],
    careersUnlocked: ["Equity Research Analyst", "Investment Banker", "Wealth Manager / Certified Financial Planner", "Financial Analyst"],
  },

  /* ═══════════════════════════════════════════════════════════════
     DEFENSE
     ═══════════════════════════════════════════════════════════════ */
  {
    name: "CDS",
    fullName: "Combined Defence Services Examination",
    category: "entrance",
    field: "defense",
    level: "defense",
    examDate: "2026-02-08",
    applicationStart: "2025-11-15",
    applicationEnd: "2025-12-15",
    eligibility: "UG degree. Age 19-25 (varies by branch — IMA, OTA, INA, AFA).",
    pattern: "English + GK + Math · 100 MCQs each · 2 hrs each",
    fees: 200,
    officialWebsite: "https://upsc.gov.in",
    description: "Officer-entry into Army (IMA / OTA), Navy (INA), Air Force (AFA). Conducted twice yearly by UPSC.",
    careersUnlocked: ["Defense Officer (NDA → Indian Armed Forces)"],
    collegesAccepting: ["IMA Dehradun", "OTA Chennai", "INA Ezhimala", "AFA Hyderabad"],
  },
  {
    name: "AFCAT",
    fullName: "Air Force Common Admission Test",
    category: "entrance",
    field: "defense",
    level: "defense",
    examDate: "2026-02-22",
    applicationStart: "2025-12-01",
    applicationEnd: "2025-12-30",
    eligibility: "UG degree (Flying); B.Tech/B.E. (Technical); UG any stream (Ground Duty). Age 20-26.",
    pattern: "GA + English + Reasoning + Quant · 100 MCQs · 2 hrs · CBT",
    fees: 550,
    officialWebsite: "https://afcat.cdac.in",
    description: "Indian Air Force officer entry — Flying, Technical, Ground Duty branches. Two cycles per year.",
    careersUnlocked: ["Defense Officer (NDA → Indian Armed Forces)", "Pilot"],
    collegesAccepting: ["AFA Hyderabad"],
  },
  {
    name: "Indian Coast Guard Navik",
    fullName: "Indian Coast Guard Navik (GD/DB) Recruitment",
    category: "entrance",
    field: "defense",
    level: "defense",
    applicationStart: "2026-01-15",
    applicationEnd: "2026-02-05",
    eligibility: "Class 12 with PCM (Navik GD) or Class 10 (Navik DB). Age 18-22.",
    pattern: "Stage 1 Computer-Based Test + Stage 2 Physical + Document Verification + Medical",
    fees: 300,
    officialWebsite: "https://joinindiancoastguard.cdac.in",
    description: "Sailor-level entry into Indian Coast Guard. Two cycles per year. Tough physical tests.",
    careersUnlocked: ["Defense Officer (NDA → Indian Armed Forces)"],
  },

  /* ═══════════════════════════════════════════════════════════════
     CIVIL SERVICES + BANKING
     ═══════════════════════════════════════════════════════════════ */
  {
    name: "IBPS PO",
    fullName: "Institute of Banking Personnel Selection — Probationary Officer",
    category: "entrance",
    field: "banking",
    level: "PG",
    examDate: "2026-10-12",
    applicationStart: "2026-08-01",
    applicationEnd: "2026-08-25",
    eligibility: "UG degree (any discipline). Age 20-30.",
    pattern: "Prelims (English + Quant + Reasoning, 100 Q, 1 hr) → Mains (5 sections, 200 Q, 3.5 hrs) → Interview",
    fees: 850,
    officialWebsite: "https://www.ibps.in",
    description: "Officer entry into 11 public sector banks (PNB, BoB, Canara, Indian Bank, etc.). ~5,000 vacancies annually.",
    careersUnlocked: ["Bank PO / Banking Officer"],
  },
  {
    name: "SBI PO",
    fullName: "State Bank of India — Probationary Officer",
    category: "entrance",
    field: "banking",
    level: "PG",
    applicationStart: "2026-04-01",
    applicationEnd: "2026-04-25",
    eligibility: "UG degree. Age 21-30.",
    pattern: "Prelims → Mains (Reasoning + DA + GA + English + Descriptive) → Group Exercise + Interview",
    fees: 750,
    officialWebsite: "https://sbi.co.in/careers",
    description: "Most prestigious bank PO exam in India. ~2,000 seats. Salary + posting nationwide.",
    careersUnlocked: ["Bank PO / Banking Officer"],
  },
  {
    name: "RBI Grade B",
    fullName: "Reserve Bank of India — Grade B Officer",
    category: "entrance",
    field: "banking",
    level: "PG",
    examDate: "2026-08-15",
    applicationStart: "2026-06-01",
    applicationEnd: "2026-06-30",
    eligibility: "UG degree ≥60% (50% for SC/ST). Age 21-30.",
    pattern: "Phase 1 (GA + English + Quant + Reasoning) → Phase 2 (Economic & Social Issues + ESM + Finance) → Interview",
    fees: 850,
    officialWebsite: "https://opportunities.rbi.org.in",
    description: "Entry to RBI as a Grade B officer — research, policy, regulation. Most coveted banking exam.",
    careersUnlocked: ["RBI Grade B Officer", "Economist"],
  },

  /* ═══════════════════════════════════════════════════════════════
     RESEARCH / PURE SCIENCES
     ═══════════════════════════════════════════════════════════════ */
  {
    name: "GATE",
    fullName: "Graduate Aptitude Test in Engineering",
    category: "entrance",
    field: "engineering",
    level: "PG",
    examDate: "2026-02-01",
    applicationStart: "2025-08-25",
    applicationEnd: "2025-10-05",
    eligibility: "B.E./B.Tech (final year or completed) OR M.Sc.",
    pattern: "30 subject papers · 65 Q · 3 hrs · CBT · GA (15 marks) + Subject (85 marks)",
    fees: 1850,
    officialWebsite: "https://gate2026.iitg.ac.in",
    description: "Gateway to M.Tech at IITs/NITs + PSU recruitment (BHEL, ONGC, IOCL, GAIL, etc.). Score valid 3 years.",
    careersUnlocked: ["Mechanical Engineer", "Civil Engineer", "Electrical Engineer", "Software Engineer", "Aerospace Engineer"],
    collegesAccepting: ["IIT Bombay", "IIT Delhi", "IIT Madras", "IIT Kanpur", "IISc Bangalore"],
  },
  {
    name: "IIT JAM",
    fullName: "Joint Admission Test for Master's",
    category: "entrance",
    field: "research",
    level: "PG",
    examDate: "2026-02-09",
    applicationStart: "2025-09-05",
    applicationEnd: "2025-10-15",
    eligibility: "Bachelor's in Science (or final year). Subject-specific reqs.",
    pattern: "MCQ + MSQ + NAT · 60 Q · 3 hrs · CBT · 7 papers (Physics, Chem, Math, Bio, etc.)",
    fees: 1800,
    officialWebsite: "https://jam.iitb.ac.in",
    description: "M.Sc admission at IITs + IISc + NITs. Bridge from BSc to research career.",
    careersUnlocked: ["Research Scientist", "Marine Biologist", "Climate Scientist", "Astrophysicist / Astronomer"],
    collegesAccepting: ["IIT Bombay", "IIT Delhi", "IIT Kanpur", "IISc Bangalore"],
  },

  /* ═══════════════════════════════════════════════════════════════
     GENERAL UNIVERSITY
     ═══════════════════════════════════════════════════════════════ */
  {
    name: "CUET UG",
    fullName: "Common University Entrance Test — Undergraduate",
    category: "entrance",
    field: "general",
    level: "UG",
    examDate: "2026-05-13",
    applicationStart: "2026-02-15",
    applicationEnd: "2026-03-15",
    eligibility: "Class 12 pass.",
    pattern: "Sec 1 Language + Sec 2 Domain (up to 6 subjects) + Sec 3 General Test · 50 MCQs each · CBT",
    fees: 1000,
    officialWebsite: "https://cuet.nta.nic.in",
    description: "Single window for UG admission to 250+ central + state + private universities — DU, BHU, JNU, Jamia, etc.",
    careersUnlocked: ["Lawyer", "Economist", "Psychologist", "Historian / Archaeologist", "Public Policy Analyst"],
    collegesAccepting: ["Delhi University", "BHU Varanasi", "Jamia Millia Islamia", "Hyderabad Central University", "Pondicherry University"],
  },
  {
    name: "CUET PG",
    fullName: "Common University Entrance Test — Postgraduate",
    category: "entrance",
    field: "general",
    level: "PG",
    examDate: "2026-03-25",
    applicationStart: "2025-12-15",
    applicationEnd: "2026-02-05",
    eligibility: "UG degree.",
    pattern: "Subject-specific 100 MCQs · 1.75 hrs · CBT",
    fees: 1200,
    officialWebsite: "https://cuet.nta.nic.in",
    description: "PG admission to central + many state universities. Replaces individual entrance tests.",
    careersUnlocked: ["Public Policy Analyst", "Translator / Conference Interpreter", "Museum Curator / Archivist", "Librarian / Information Scientist"],
  },

  /* ═══════════════════════════════════════════════════════════════
     INTERNATIONAL — for studying abroad
     ═══════════════════════════════════════════════════════════════ */
  {
    name: "SAT",
    fullName: "Scholastic Assessment Test",
    category: "entrance",
    field: "general",
    level: "UG",
    international: true,
    applicationStart: "Year-round",
    applicationEnd: "5 weeks before chosen date",
    eligibility: "No formal eligibility. Best taken in Class 11 / early Class 12.",
    pattern: "Digital SAT — Reading & Writing (64 Q) + Math (44 Q) · 2 hrs 14 min · 400-1600 scale · Adaptive",
    fees: 9000,
    officialWebsite: "https://www.collegeboard.org",
    description: "Standard test for US undergrad admission. Also accepted by IIT-DASA, BITS Pilani, Ashoka, Krea + Singapore + UAE + Hong Kong unis.",
    applyHow: [
      "Create College Board account (collegeboard.org)",
      "Choose test date + India centre (held 7x/year)",
      "Pay $103 (+$43 international fee) ≈ ₹12,000",
      "Bring ID + admit card on test day, ~3 hr session",
      "Scores released 2 weeks later, free 4-college report",
      "Best score → use for college apps via Common App",
    ],
    careersUnlocked: ["Software Engineer", "Investment Banker", "AI/ML Engineer", "Research Scientist"],
    collegesAccepting: ["IIT Bombay (DASA)", "BITS Pilani", "Ashoka Univ", "NUS Singapore", "Harvard", "MIT", "Stanford"],
  },
  {
    name: "ACT",
    fullName: "American College Testing",
    category: "entrance",
    field: "general",
    level: "UG",
    international: true,
    eligibility: "Same as SAT — Class 11/12.",
    pattern: "English + Math + Reading + Science · Plus optional Writing · ~3 hrs · 1-36 scale",
    fees: 14000,
    officialWebsite: "https://www.act.org",
    description: "Alternative to SAT for US undergrad. Includes a Science section (data interpretation, not facts). Indian students less commonly use it.",
    careersUnlocked: ["Software Engineer", "Research Scientist"],
  },
  {
    name: "TOEFL iBT",
    fullName: "Test of English as a Foreign Language — Internet Based",
    category: "entrance",
    field: "language",
    level: "language",
    international: true,
    applicationStart: "Year-round",
    applicationEnd: "7 days before chosen date",
    eligibility: "No formal eligibility.",
    pattern: "Reading + Listening + Speaking + Writing · 2 hrs · Score 0-120",
    fees: 16500,
    officialWebsite: "https://www.ets.org/toefl",
    description: "English proficiency proof required by US universities. Score valid 2 years.",
    careersUnlocked: ["Software Engineer", "Research Scientist", "Investment Banker"],
  },
  {
    name: "IELTS",
    fullName: "International English Language Testing System",
    category: "entrance",
    field: "language",
    level: "language",
    international: true,
    applicationStart: "Year-round",
    applicationEnd: "Same week as chosen date",
    eligibility: "No formal eligibility.",
    pattern: "Listening + Reading + Writing + Speaking · 2 hrs 45 min · Band 0-9",
    fees: 17000,
    officialWebsite: "https://www.idp.com/india/ielts",
    description: "Most accepted English proficiency test for UK, Canada, Australia, NZ universities + immigration. Score valid 2 years.",
    applyHow: [
      "Register on idp.com/india/ielts or britishcouncil.in",
      "Choose Academic (for study) or General Training (immigration)",
      "Pay ₹17,000 fee online",
      "Pick test centre + date (held 4x/month in major cities)",
      "Online or paper format option",
      "Results in 3-5 days (online) or 13 days (paper)",
    ],
    careersUnlocked: ["Software Engineer", "Research Scientist"],
  },
  {
    name: "Duolingo English Test",
    fullName: "Duolingo English Test (online)",
    category: "entrance",
    field: "language",
    level: "language",
    international: true,
    applicationStart: "Year-round",
    eligibility: "No formal eligibility. Internet + webcam needed.",
    pattern: "Adaptive online test, ~1 hr · Score 10-160 · No test centre — take from home",
    fees: 5000,
    officialWebsite: "https://englishtest.duolingo.com",
    description: "Affordable, fast English proficiency test. Accepted by 5,500+ universities (mostly US + Canada). Results in 48 hrs.",
    careersUnlocked: ["Software Engineer", "Research Scientist"],
  },
  {
    name: "GRE",
    fullName: "Graduate Record Examinations",
    category: "entrance",
    field: "general",
    level: "PG",
    international: true,
    applicationStart: "Year-round",
    eligibility: "UG degree (or final year).",
    pattern: "Verbal Reasoning + Quant Reasoning + Analytical Writing · ~1 hr 58 min (shortened in 2023) · Score 130-170 per section",
    fees: 18500,
    officialWebsite: "https://www.ets.org/gre",
    description: "Required for MS / PhD admission in US (+ some EU + Singapore). Score valid 5 years.",
    careersUnlocked: ["AI/ML Engineer", "Data Scientist", "Research Scientist", "Quantum Computing Researcher"],
  },
  {
    name: "GMAT Focus Edition",
    fullName: "Graduate Management Admission Test",
    category: "entrance",
    field: "management",
    level: "PG",
    international: true,
    applicationStart: "Year-round",
    eligibility: "UG degree.",
    pattern: "Quant + Verbal + Data Insights · 2 hrs 15 min · 205-805 scale · Adaptive",
    fees: 23500,
    officialWebsite: "https://www.mba.com/gmat",
    description: "MBA entrance — accepted at INSEAD, Harvard, Wharton, ISB Hyderabad, IIM-A/B/C 1-yr programs.",
    careersUnlocked: ["Investment Banker", "Marketing Manager", "Brand Manager (FMCG / Consumer)"],
    collegesAccepting: ["ISB Hyderabad", "IIM Ahmedabad (PGPX)", "INSEAD", "Harvard Business School"],
  },
  {
    name: "LSAT (US)",
    fullName: "Law School Admission Test",
    category: "entrance",
    field: "law",
    level: "PG",
    international: true,
    applicationStart: "Year-round",
    eligibility: "UG degree (for US JD).",
    pattern: "Logical Reasoning + Analytical Reasoning + Reading Comp + Writing · ~3 hrs · 120-180 scale",
    fees: 18000,
    officialWebsite: "https://www.lsac.org",
    description: "US law school admission. Distinct from LSAT India (used for some Indian law colleges).",
    careersUnlocked: ["Lawyer", "Constitutional / Human Rights Lawyer"],
  },
  {
    name: "MCAT",
    fullName: "Medical College Admission Test",
    category: "entrance",
    field: "medical",
    level: "PG",
    international: true,
    applicationStart: "Year-round",
    eligibility: "UG degree, typically with pre-med prerequisites (Bio, Chem, Org Chem, Physics, Biochem, Psych).",
    pattern: "Biological & Biochemical + Chemical & Physical + Psychological/Social + Critical Analysis · 7.5 hrs · 472-528 scale",
    fees: 28000,
    officialWebsite: "https://students-residents.aamc.org/mcat",
    description: "US + Canada medical school entrance. Requires 4-yr undergrad + MCAT for US MD. Indian MBBS isn't a substitute.",
    careersUnlocked: ["Doctor (MBBS)", "Cardiologist", "Neurologist"],
  },
  {
    name: "UCAT",
    fullName: "University Clinical Aptitude Test",
    category: "entrance",
    field: "medical",
    level: "UG",
    international: true,
    examDate: "2026-07-15",
    applicationStart: "2026-05-01",
    applicationEnd: "2026-09-15",
    eligibility: "Aspiring to UK/Australia/NZ medical or dental schools.",
    pattern: "Verbal Reasoning + Decision Making + Quant + Abstract Reasoning + Situational Judgement · 2 hrs · CBT",
    fees: 8500,
    officialWebsite: "https://www.ucat.ac.uk",
    description: "Required for ~30 UK medical/dental schools + most Australian/NZ ones. Score valid only 1 year.",
    careersUnlocked: ["Doctor (MBBS)"],
  },
  {
    name: "Oxford TSA / MAT / PAT",
    fullName: "Oxford Admissions Tests (TSA / MAT / PAT)",
    category: "entrance",
    field: "general",
    level: "UG",
    international: true,
    examDate: "2026-10-19",
    applicationStart: "2026-09-01",
    applicationEnd: "2026-10-05",
    eligibility: "Applying to Oxford UG.",
    pattern: "TSA (Thinking Skills) for PPE/Econ etc. · MAT for Math/CS · PAT for Physics/Engg · ~2 hrs each",
    fees: 0,
    officialWebsite: "https://www.ox.ac.uk/admissions",
    description: "Subject-specific admission tests for University of Oxford undergrad. Free for Indian candidates at British Council centres.",
    careersUnlocked: ["Research Scientist", "AI/ML Engineer", "Quantum Computing Researcher", "Economist"],
    collegesAccepting: ["University of Oxford"],
  },
  {
    name: "JLPT N5-N1",
    fullName: "Japanese Language Proficiency Test",
    category: "entrance",
    field: "language",
    level: "language",
    international: true,
    examDate: "2026-07-05",
    applicationStart: "2026-03-15",
    applicationEnd: "2026-04-15",
    eligibility: "No formal — N5 (beginner) to N1 (advanced).",
    pattern: "Vocabulary + Grammar + Reading + Listening · ~2 hrs · 5 levels (N5 easiest, N1 hardest)",
    fees: 1200,
    officialWebsite: "https://www.jlpt.jp",
    description: "Official Japanese proficiency cert. N2/N1 required for jobs at Japanese companies + Monbukagakusho scholarship.",
    careersUnlocked: ["Translator / Conference Interpreter", "Software Engineer"],
  },
];
