/**
 * Government + private scholarships available to Indian school students.
 * Amounts in INR. Deadlines are approximate annual cycles.
 */

export type SeedScholarship = {
  name: string;
  provider: string;
  type: "govt" | "private" | "merit" | "need" | "nri";
  state: string | null; // null = all-India
  amount: number; // approximate annual (in INR)
  eligibility: string;
  applicationLink?: string;
  deadline?: string;
  documents: string[];
  /** Open to NRI / Overseas Indian students */
  nriEligible?: boolean;
  /** Specific NRI country target (null = open to NRIs in any country) */
  targetCountry?: string | null;
};

export const SCHOLARSHIPS: SeedScholarship[] = [
  /* ─── National-level govt ─── */
  {
    name: "NMMS",
    provider: "Ministry of Education, Govt of India",
    type: "govt",
    state: null,
    amount: 12000,
    eligibility: "Class 9-12 students from families earning <₹3.5L/year. Min 55% in Class 8.",
    applicationLink: "https://scholarships.gov.in",
    deadline: "2026-10-31",
    documents: ["Income certificate", "Marksheet", "Aadhaar", "Bank passbook", "Caste cert (if applicable)"],
  },
  {
    name: "National Scholarship Portal (NSP) — Pre-Matric",
    provider: "Ministry of Minority Affairs",
    type: "govt",
    state: null,
    amount: 7000,
    eligibility: "Class 1-10 students from minority communities, family income <₹1L.",
    applicationLink: "https://scholarships.gov.in",
    deadline: "2026-12-15",
    documents: ["Caste/Minority cert", "Income cert", "Marksheet", "Bank passbook"],
  },
  {
    name: "NSP — Post-Matric",
    provider: "Ministry of Social Justice",
    type: "govt",
    state: null,
    amount: 20000,
    eligibility: "Class 11 onwards, SC/ST/OBC/Minority, family income limits vary.",
    applicationLink: "https://scholarships.gov.in",
    deadline: "2026-12-15",
    documents: ["Caste cert", "Income cert", "Marksheet", "Bank passbook"],
  },
  {
    name: "Central Sector Scholarship",
    provider: "Ministry of Education",
    type: "merit",
    state: null,
    amount: 12000,
    eligibility: "Top 80 percentile in Class 12 + family income <₹4.5L. For UG.",
    applicationLink: "https://scholarships.gov.in",
    deadline: "2026-10-31",
    documents: ["Class 12 marksheet", "Income cert", "Aadhaar", "Bank details"],
  },
  {
    name: "INSPIRE-SHE",
    provider: "Department of Science & Technology",
    type: "merit",
    state: null,
    amount: 80000,
    eligibility: "Top 1% in Class 12 board OR top performers in JEE/NEET. Pursuing BSc/Integrated MSc in natural/basic sciences.",
    applicationLink: "https://online-inspire.gov.in",
    deadline: "2026-07-31",
    documents: ["Class 12 marksheet", "College admission proof", "Aadhaar", "Bank details"],
  },
  {
    name: "Prime Minister's Scholarship Scheme (PMSS)",
    provider: "Ministry of Defence",
    type: "govt",
    state: null,
    amount: 30000,
    eligibility: "Wards/widows of ex-servicemen / war widows, pursuing UG/PG.",
    applicationLink: "https://www.ksb.gov.in",
    deadline: "2026-11-30",
    documents: ["Ex-servicemen cert", "Class 12 marksheet", "Admission proof"],
  },
  {
    name: "Begum Hazrat Mahal Scholarship",
    provider: "Ministry of Minority Affairs",
    type: "govt",
    state: null,
    amount: 12000,
    eligibility: "Girls from minority communities in Class 9-12. Min 50% in Class 8/10.",
    applicationLink: "https://scholarships.gov.in",
    deadline: "2026-12-31",
    documents: ["Income cert", "Minority cert", "Marksheet", "Aadhaar"],
  },

  /* ─── Private / corporate ─── */
  {
    name: "Reliance Foundation Scholarship",
    provider: "Reliance Foundation",
    type: "private",
    state: null,
    amount: 200000,
    eligibility: "Class 12 pass for UG, family income <₹15L preferred. Merit + need based.",
    applicationLink: "https://www.scholarships.reliancefoundation.org",
    deadline: "2026-09-30",
    documents: ["Class 12 marksheet", "College admission letter", "Income cert", "Statement of purpose"],
    nriEligible: true,
  },
  {
    name: "L'Oréal India For Young Women in Science",
    provider: "L'Oréal India",
    type: "private",
    state: null,
    amount: 250000,
    eligibility: "Girls who passed Class 12 with PCM/PCB ≥85%, family income <₹6L. Pursuing UG in science.",
    applicationLink: "https://www.scholarshipsindia.com",
    deadline: "2026-09-15",
    documents: ["Class 12 marksheet", "Income proof", "Essay", "Admission letter"],
  },
  {
    name: "Aditya Birla Scholarship",
    provider: "Aditya Birla Group",
    type: "private",
    state: null,
    amount: 175000,
    eligibility: "Selected B-school + engineering students (typically IIM/IIT). Need-based component.",
    applicationLink: "https://www.adityabirlascholars.net",
    deadline: "2026-07-31",
    documents: ["Admission letter", "Class 12 marksheet", "Income proof"],
    nriEligible: true,
  },
  {
    name: "Tata Trusts Education Grants",
    provider: "Tata Trusts",
    type: "private",
    state: null,
    amount: 50000,
    eligibility: "Class 10+ students, need-based.",
    applicationLink: "https://www.tatatrusts.org",
    deadline: "2026-07-15",
    documents: ["Income cert", "Admission proof", "Latest marksheet"],
  },
  {
    name: "Buddy4Study Scholarships",
    provider: "Buddy4Study Foundation",
    type: "private",
    state: null,
    amount: 30000,
    eligibility: "Class 8 onwards. Various categories — merit, need, sports.",
    applicationLink: "https://www.buddy4study.com",
    deadline: "Rolling",
    documents: ["Latest marksheet", "Income cert (some)", "ID proof"],
  },
  {
    name: "Vidyasaarathi Scholarship",
    provider: "NSDL e-Governance Foundation",
    type: "private",
    state: null,
    amount: 75000,
    eligibility: "Class 12+ for UG/PG. Multiple sub-schemes.",
    applicationLink: "https://www.vidyasaarathi.co.in",
    deadline: "Varies",
    documents: ["Admission letter", "Marksheets", "Income cert"],
  },

  /* ─── State-level samples ─── */
  {
    name: "Kerala Higher Education Scholarship",
    provider: "Govt of Kerala",
    type: "govt",
    state: "Kerala",
    amount: 12000,
    eligibility: "Kerala domiciled, Class 11 onwards, family income <₹2.5L.",
    applicationLink: "https://www.dcescholarship.kerala.gov.in",
    deadline: "2026-10-31",
    documents: ["Domicile cert", "Income cert", "Latest marksheet", "Aadhaar"],
  },
  {
    name: "Tamil Nadu Free Education Scheme",
    provider: "Govt of Tamil Nadu",
    type: "govt",
    state: "Tamil Nadu",
    amount: 25000,
    eligibility: "Tamil Nadu domiciled, family income <₹2L, first graduate in family.",
    applicationLink: "https://www.tn.gov.in",
    deadline: "2026-09-30",
    documents: ["Domicile cert", "Income cert", "First-graduate cert"],
  },
  {
    name: "Karnataka SSP",
    provider: "Govt of Karnataka",
    type: "govt",
    state: "Karnataka",
    amount: 11000,
    eligibility: "Karnataka domiciled, all categories. Various sub-schemes by category.",
    applicationLink: "https://ssp.postmatric.karnataka.gov.in",
    deadline: "2026-10-30",
    documents: ["Domicile cert", "Income cert", "Caste cert"],
  },
  {
    name: "Maharashtra Post-Matric Scholarship",
    provider: "Govt of Maharashtra",
    type: "govt",
    state: "Maharashtra",
    amount: 15000,
    eligibility: "Maharashtra SC/ST/OBC, Class 11+. Income limits vary.",
    applicationLink: "https://mahadbt.maharashtra.gov.in",
    deadline: "2026-12-31",
    documents: ["Caste cert", "Income cert", "Domicile cert", "Marksheets"],
  },
  {
    name: "UP Scholarship",
    provider: "Govt of Uttar Pradesh",
    type: "govt",
    state: "Uttar Pradesh",
    amount: 12000,
    eligibility: "UP domiciled, Class 9 onwards, SC/ST/OBC/General category-wise income limits.",
    applicationLink: "https://scholarship.up.gov.in",
    deadline: "2026-11-30",
    documents: ["Caste cert", "Income cert", "Domicile cert"],
  },
  {
    name: "West Bengal Aikyashree Scholarship",
    provider: "Govt of West Bengal",
    type: "govt",
    state: "West Bengal",
    amount: 12000,
    eligibility: "WB minority community students, Class 1-12, family income <₹2L.",
    applicationLink: "https://wbmdfcscholarship.org",
    deadline: "2026-12-31",
    documents: ["Minority cert", "Income cert", "Marksheet"],
  },

  /* ─── International / disability ─── */
  {
    name: "PM-YASASVI",
    provider: "Ministry of Social Justice",
    type: "govt",
    state: null,
    amount: 125000,
    eligibility: "OBC/EBC/DNT students, Class 9 & 11 (top 1L families with income <₹2.5L).",
    applicationLink: "https://yet.nta.ac.in",
    deadline: "2026-08-31",
    documents: ["Caste cert", "Income cert", "Class 8/10 marksheet"],
  },
  {
    name: "Pre-Matric Scholarship for Students with Disabilities",
    provider: "Ministry of Social Justice",
    type: "govt",
    state: null,
    amount: 5000,
    eligibility: "Class 9-10 with min 40% disability, family income <₹2.5L.",
    applicationLink: "https://scholarships.gov.in",
    deadline: "2026-11-30",
    documents: ["Disability cert", "Income cert", "Marksheet"],
  },

  /* ─── NRI / Overseas Indian scholarships ─── */
  {
    name: "Scholarship for Diaspora Children (SPDC)",
    provider: "Ministry of External Affairs, Govt of India",
    type: "nri",
    state: null,
    amount: 332000,
    eligibility:
      "NRI / PIO / OCI students with family income ≤ USD 100K/yr. Pursuing UG in India in selected courses. Max tuition + living grant up to $4,000/yr.",
    applicationLink: "https://www.spdcindia.gov.in",
    deadline: "2026-09-30",
    documents: ["NRI/PIO/OCI proof", "Family income statement (USD)", "Class 12 marksheet", "Admission letter", "Passport copy"],
    nriEligible: true,
  },
  {
    name: "ICCR Scholarship for International Students",
    provider: "Indian Council for Cultural Relations",
    type: "nri",
    state: null,
    amount: 300000,
    eligibility:
      "Foreign nationals + OCI/PIO students seeking UG/PG in India. Country quotas vary. Includes tuition waiver + monthly stipend ₹18,000.",
    applicationLink: "https://a2ascholarships.iccr.gov.in",
    deadline: "2026-04-30",
    documents: ["Nationality proof", "Class 12 transcript", "Recommendation letters", "Medical fitness cert"],
    nriEligible: true,
  },
  {
    name: "Gulf Education Loan + Scholarship (Federal Bank NRI)",
    provider: "Federal Bank — Gulf NRI Cell",
    type: "nri",
    state: null,
    amount: 1500000,
    eligibility:
      "NRI students of Indian origin in UAE / Saudi / Qatar / Oman / Kuwait / Bahrain. Available for UG abroad or in India. Subsidized rate + partial grant.",
    applicationLink: "https://www.federalbank.co.in/nri-banking",
    deadline: "Rolling",
    documents: ["NRI/OCI proof", "Parent UAE residency", "Admission letter", "Income proof from sponsor"],
    nriEligible: true,
    targetCountry: "United Arab Emirates",
  },
  {
    name: "Sharjah Ruler Indian School Scholarship",
    provider: "Sharjah Indian Schools Trust",
    type: "nri",
    state: null,
    amount: 200000,
    eligibility:
      "Indian students in UAE Sharjah Indian schools pursuing UG. Merit + need based. Apply through school CBSE coordinator.",
    applicationLink: "https://www.dpis.sch.ae",
    deadline: "Annual cycle — Apr",
    documents: ["UAE residency", "School recommendation", "Class 12 marksheet", "Parent income cert"],
    nriEligible: true,
    targetCountry: "United Arab Emirates",
  },
  {
    name: "OCI/PIO Direct Admission of Students Abroad (DASA)",
    provider: "Ministry of Education — DASA scheme",
    type: "nri",
    state: null,
    amount: 0,
    eligibility:
      "OCI/PIO/NRI students for B.Tech at NITs/IIITs/SPAs. No tuition grant — but unique cutoff path (SAT score) + lower than domestic Indian competition. ~10-15% supernumerary seats.",
    applicationLink: "https://www.dasanit.org",
    deadline: "2026-06-30",
    documents: ["NRI/OCI proof", "SAT score (>1450 typical)", "Class 12 marksheet", "Passport copy"],
    nriEligible: true,
  },
  {
    name: "Khalifa University Scholarship (UAE)",
    provider: "Khalifa University of Science & Technology",
    type: "nri",
    state: null,
    amount: 2500000,
    eligibility:
      "Top Class 12 PCM students globally for UG Engineering at Khalifa Uni, Abu Dhabi. Covers full tuition + monthly stipend + accommodation. Highly competitive.",
    applicationLink: "https://www.ku.ac.ae/admissions",
    deadline: "2026-03-31",
    documents: ["Class 12 transcript (predicted + actual)", "SAT score", "TOEFL/IELTS", "Recommendation letters"],
    nriEligible: true,
    targetCountry: "United Arab Emirates",
  },
  {
    name: "Higher Education Loan — NRI (HDFC Credila)",
    provider: "HDFC Credila",
    type: "nri",
    state: null,
    amount: 7500000,
    eligibility:
      "NRI students for higher education in India OR abroad (US/UK/Canada/Australia). Co-signed by Indian parent/relative. Up to ₹75L loan at ~10-11% interest.",
    applicationLink: "https://www.hdfccredila.com",
    deadline: "Rolling",
    documents: ["NRI/OCI proof", "Admission letter", "Co-signer KYC + ITR", "Sponsor income proof"],
    nriEligible: true,
  },
  {
    name: "Manipal NRI Scholarship",
    provider: "Manipal Academy of Higher Education",
    type: "nri",
    state: null,
    amount: 1000000,
    eligibility:
      "Top-ranking NRI students admitted to MAHE programs. Merit-based partial fee waiver. Decided post-admission.",
    applicationLink: "https://manipal.edu/mu/admission.html",
    deadline: "Post-admission review",
    documents: ["MAHE admission offer", "NRI/OCI proof", "Class 12 marksheet (>90%)"],
    nriEligible: true,
  },
];
